server:
  port: 9527 # 这个端口要和vue项目里vue.config.js里的devServer里面配置的相同
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abmxkok199867
    url: jdbc:mysql://localhost:3306/exam?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    # 调试的时候用，用于打印完成SQL语句(但是不打印参数),联合下面的logging.level一同打印最完整的SQL信息(语句+参数)
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: /api/user/register,/api/user/login

# SQL语句打印(能打印参数，设置为trace是打印完整语句，默认我们就关掉吧)
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: off
